# services:
#   - type: web
#     name: airtable-form-builder-api
#     env: node
#     plan: free
#     buildCommand: cd server && npm install
#     startCommand: cd server && npm start
#     envVars:
#       - key: NODE_ENV
#         value: production
#       - key: PORT
#         value: 4000
#       - key: MONGO_URI
#         fromDatabase:
#           name: mongodb
#           property: connectionString
#       - key: JWT_SECRET
#         generateValue: true
#       - key: AIRTABLE_CLIENT_ID
#         sync: false
#       - key: AIRTABLE_CLIENT_SECRET
#         sync: false
#       - key: AIRTABLE_OAUTH_REDIRECT_URI
#         sync: false
#       - key: S3_BUCKET
#         sync: false
#       - key: S3_REGION
#         sync: false
#       - key: S3_ACCESS_KEY_ID
#         sync: false
#       - key: S3_SECRET_ACCESS_KEY
#         sync: false

# databases:
#   - name: mongodb
#     plan: free
services:
  - type: web
    name: airtable-form-builder
    env: node
    plan: free
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000   # Render injects its own PORT, but keeping fallback is fine
      - key: MONGO_URI
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: AIRTABLE_CLIENT_ID
        sync: false
      - key: AIRTABLE_CLIENT_SECRET
        sync: false
      - key: AIRTABLE_OAUTH_REDIRECT_URI
        sync: false
      - key: CLIENT_URL
        value: https://airtable-form-builder-jjcx.onrender.com
      - key: SERVER_URL
        value: https://airtable-form-builder-jjcx.onrender.com
      - key: S3_BUCKET
        sync: false
      - key: S3_REGION
        sync: false
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false

databases:
  - name: mongodb
    plan: free
